#version : "3.9"
#services :
#  backend:
#    image: '#image'
#    container_name: docercompas
#    restart: always
#    ports:
#      - "80:2025"
#    environment:
#      SPRING_PROFILES_ACTIVE: main
#      SERVER_PORT: 2025
#      POSTGRES_DB: jdbc:postgresql://13.51.162.67:5432/postgres
#      POSTGRES_USER: demouser
#      POSTGRES_PASSWORD: demopass
#  database:
#    image: postgres:15
#    restart: always
#    container_name : database
#    ports:
#      -  "5432:5432"
#    environment:
#      POSTGRES_USER: demouser
#      POSTGRES_PASSWORD: demopass
#    volumes:
#      - db_data:/var/lib/postgresql/data
#volumes:
#  db_data:
version: "3.9"
services:
  backend:
    image: '#image'
    container_name: dockercompas
    restart: always
    ports:
      - "80:2025"
    environment:
      SPRING_PROFILES_ACTIVE: main
      SERVER_PORT: 2025
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: demouser
      SPRING_DATASOURCE_PASSWORD: demopass
    depends_on:
      - database
  database:
    image: postgres:15
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: demopass
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
